theme = "gruvbox_dark_soft"

[editor]
line-number = "relative"
mouse = false
true-color = true
bufferline = "multiple"

[editor.indent-guides]
# character = "â•"
# character = "â˜"
# character = "â‹®"
# character = "â"
# character = "â¦š"
# character = "â¸½"
# character = "â¿"
# character = "âŸŠ"
character = "ğŸ­°"
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[keys.normal]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
x = ["extend_line_down", "extend_to_line_bounds"]
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
x = ["extend_line_down", "extend_to_line_bounds"]
